language: python
python: 3.7
install:
- pip install Sphinx
- pip install git+https://github.com/bashtage/sphinx-material
- pip install m2rr
script:
- make html
- cp -r images _build/html/
- cp CNAME _build/html/
- touch _build/html/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    all_branches: true
  local_dir: _build/html
